### ISSUE TITLE
Creation time is not available on this platform currently

### ISSUE THREAD

**Issue by N3xed** [tropicbliss/cuprite#1]
Creating backup fails with the following error:

```
Error: Failed to truncate target directory

Caused by:
    creation time is not available on this platform currently
```

I really don't know why this happens.

Running on `Linux 5.10.28-Unraid`

**Comment by tropicbliss** [comment]
I'll push out a fix for that soon

**Comment by tropicbliss** [comment]
Alright, I pushed out a fix. Download the latest version on crates.io using `cargo install cuprite`. Alternatively, please wait for a few more hours to provide you with a pre-compiled binary as I don't have access to my main computer rn.

EDIT: Just uploaded the latest binary.

**Comment by N3xed** [comment]
Now it works, thanks!
